### ISSUE TITLE
Ignore particular colors

### ISSUE THREAD

**Issue by gampleman** [abe33/atom-pigments#126]
Our product does some stuff with Microsoft Azure. As you may imagine, the string `Microsoft Azure` is littered all over the code base. I would really like to be able to set Azure as an ignored color, since our design doesn't use azure as a color.

**Comment by abe33** [comment]
Hi @gampleman, looks you got the same issue than in issue #110, you can [limit the scope of Pigments](https://github.com/abe33/atom-pigments#defining-where-pigments-applies) by specifying the file extension to support or the scope to ignore.

**Comment by gampleman** [comment]
Yeah but I can't easily do that, because Azure is mentioned in files that contain valid color references (i.e. charting code).

**Comment by abe33** [comment]
Hmm, this should do the trick until I think of a better solution: 

```css
atom-text-editor::shadow pigments-marker::shadow .region[style*="background-color: rgb(240, 255, 255)"] {
  display: none
}
```

Put that in your user stylesheet and it will hide all the markers with the azure color.
