### ISSUE TITLE
Square dots

### ISSUE THREAD

**Issue by Mayccoll** [abe33/atom-pigments#15]
Hi, tnks for this nice plugin.
You may include square dots?

![square](https://cloud.githubusercontent.com/assets/2009698/7692388/b5cfbb74-fd89-11e4-8fd6-5d4374079766.png)

Tnks again

**Comment by abe33** [comment]
Thanks for the suggestion, I'll see to add a setting for that, for the time being you can use this rule to remove the `border-radius` on the dots in your user stylesheet: 

```less
atom-text-editor::shadow pigments-markers::shadow pigments-color-marker.dot {
  border-radius: 0;
}
```
