### ISSUE TITLE
Wrong rendering of hsl colors?

### ISSUE THREAD

**Issue by eschmid72** [abe33/atom-pigments#199]
less example:
```less
.test {
  background: hsl(285, 0.7, 0.7)
}
```

less css compiles it to:
```css
.test {
  background: #cd7de8;
}
```

Your package renders: `rgb(2,2,2)`
