### ISSUE TITLE
Ignore attribute selector values

### ISSUE THREAD

**Issue by smutnyleszek** [abe33/atom-pigments#274]
In this scenario all three are identified as color names by pigments: "white", "silver" and "black", but only "black" should be.

```css
[am-area~="white"],
[am-area~="silver"] {
    color: black;
}
```
