### ISSUE TITLE
map_get support

### ISSUE THREAD

**Issue by Julix91** [abe33/atom-pigments#307]
I'd like to have my colours displayed, even if they're stored in an array - Things like: 
`map_get($theme-colors,button-color)`

Is that possible?

**Comment by C-Bouthoorn** [comment]
Of what language is that a feature?

**Comment by dmbdesignpdx** [comment]
Yes, +1 for this. I do believe @Julix91  is referring to Sass; at least that's what I would want. 

Here's an example scenario expanding on @Julix91's request for more clarification:

```scss
$primary: #34495E;

$map: (
   orange: #FFA500,
   indigo: #4B0082,
   default: $primary
);

.example {
   color: map-get($map, default);
   // 'map-get($map, default)' is highlighted
}
```

It would also be nice for the scope to go even further (using the previous example):

```scss
@function color($var) {
   @return map-get($map, $var); 
}

.example {
   color: color(default);
   // 'color(default)' is highlighted
}
```
